version: '3.8'
services:
  postgres:

    image: postgres:12
    container_name: postgres
    #restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomerce

  spring-boot-app:
    image: openjdk:20-slim-bullseye
    container_name: spring-boot-app
    depends_on:
      - postgres
    #restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ecomerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./target/practica-spring-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]